import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'sonner'
import BottomNav from "@/components/ui/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <BottomNav />
        <Toaster
          position="bottom-left"  // Abajo a la izquierda
          offset="120px"          // <--- IMPORTANTE: Esto las levanta por encima del menú
          visibleToasts={3}       // Solo muestra 2 a la vez (para no tapar la pantalla)
          richColors              // Colores lindos (Verde/Rojo)
          theme="dark"            // Tema oscuro
          closeButton             // (Opcional) Agrega una X pequeña para cerrar
        />
      </body>
    </html>
  );
}
